pfh59/eve-whmapper

WHMapper/Models/Custom/Node/EveSystemLinkModel.cs
WHMapper/Models/Db/Enums/WHSignatureEnums.cs
WHMapper/Models/Db/Enums/WHSystemLinkEnums.cs
WHMapper/Models/Db/WHSignature.cs
WHMapper/Models/Db/WHSystemLink.cs
WHMapper/Pages/Mapper/CustomNode/EveSystemLink.cs
WHMapper/Pages/Mapper/CustomNode/EveSystemLink.razor
WHMapper/Pages/Mapper/Overview.cs
WHMapper/Pages/Mapper/Overview.razor
WHMapper/Pages/Mapper/Signatures/Import.cs
WHMapper/Pages/Mapper/Signatures/Overview.razor
WHMapper/Program.cs
WHMapper/Repositories/WHSystemLinks/IWHSystemLinkRepository.cs
WHMapper/Repositories/WHSystemLinks/WHSystemLinkRepository.cs
WHMapper/Services/WHColor/IWHColorHelper.cs
WHMapper/Services/WHColor/WHColorHelper.cs
WHMapper/WHMapper.csproj

Implementation of features #3

---

WHMapper/Program.cs

Init db with auto migration on startup class

---

WHMapper/Program.cs
WHMapper/Services/Anoik/AnoikServices.cs
WHMapper/appsettings.json

Revert "https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-l…"

---

WHMapper/Pages/Mapper/Signatures/Overview.razor
WHMapper/Services/WHSignatures/WHSignatureHelper.cs

Fix Crash when sigs fully added

---

WHMapper/Services/EveOAuthProvider/EVEOnlineAuthenticationHandler.cs
WHMapper/Shared/AccessControl.razor

Multi Character login

---

src/WHMapper/Pages/Mapper/Notes/Overview.cs
src/WHMapper/Pages/Mapper/Notes/Overview.razor
src/WHMapper/Pages/Mapper/Overview.razor
src/WHMapper/Pages/Mapper/SystemInfos/Overview.cs
src/WHMapper/Pages/Mapper/SystemInfos/Overview.razor
src/WHMapper/Pages/_Layout.cshtml

- add title
- fix #157
- refactoring some ui
- fix system info statics view when system node having no effect
- fix note when empty (auto delete)

Notes and ui fix

---

src/WHMapper/Pages/Mapper/Overview.cs
src/WHMapper/Pages/Mapper/Overview.razor
src/WHMapper/Program.cs
src/WHMapper/Services/Paste/IPasteServices.cs
src/WHMapper/Services/Paste/PasteServices.cs
src/WHMapper/Shared/AccessControl.razor
src/WHMapper/Shared/MainLayout.razor

- create a dedicated service to relay paste catches from all main layout.

fix Pasting of signatures does not work as expected #174

---

src/WHMapper.Tests/CustomGraphModel/CustomModelTest.cs
src/WHMapper.Tests/WHHelper/EveWHMapperHelperTest.cs
src/WHMapper/Hubs/IWHMapperNotificationHub.cs
src/WHMapper/Hubs/WHMapperNotificationHub.cs
src/WHMapper/Migrations/20231204092305_AddSystemStatusToWHNote.Designer.cs
src/WHMapper/Migrations/20231204092305_AddSystemStatusToWHNote.cs
src/WHMapper/Models/Custom/Node/EveSystemNodeModel.cs
src/WHMapper/Models/Db/Enums/WHSystemStatusEnums.cs
src/WHMapper/Models/Db/WHNote.cs
src/WHMapper/Pages/Mapper/CustomNode/EveSystemNode.cs
src/WHMapper/Pages/Mapper/CustomNode/EveSystemNode.razor
src/WHMapper/Pages/Mapper/Notes/Overview.cs
src/WHMapper/Pages/Mapper/Overview.cs
src/WHMapper/Services/EveMapper/EveMapperHelper.cs

Feature #175 implemented as described.

System Status feature #175

---

src/WHMapper/Models/Custom/Node/EveSystemLinkModel.cs
src/WHMapper/Pages/Mapper/CustomNode/EveSystemLink.razor

Add connection marker

---

src/WHMapper/Pages/Mapper/Overview.cs
src/WHMapper/Pages/Mapper/Signatures/Overview.cs

Multi Fixes :
- #185
- #190
- #191
- #192

Multi Fixes

---

src/WHMapper/Hubs/ConnectionMapping.cs
src/WHMapper/Hubs/WHMapperNotificationHub.cs
src/WHMapper/Models/Db/WHNote.cs
src/WHMapper/Pages/Mapper/CustomNode/EveSystemNode.razor
src/WHMapper/Pages/Mapper/Notes/Overview.razor
src/WHMapper/Pages/Mapper/Overview.cs
src/WHMapper/Pages/Mapper/Overview.razor
src/WHMapper/Pages/Mapper/RoutePlanner/Overview.razor
src/WHMapper/Pages/Mapper/Signatures/Import.cs
src/WHMapper/Pages/Mapper/Signatures/Overview.cs
src/WHMapper/Pages/Mapper/Signatures/Overview.razor
src/WHMapper/Pages/Mapper/SystemInfos/Overview.razor
src/WHMapper/Services/Paste/PasteServices.cs
src/WHMapper/Shared/MainLayout.razor
src/WHMapper/WHMapper.csproj

- update nuget package
- fix : some ui bugs
- fix : mouse map wheel zoom map scroll page down/up #212

UI refactoring

---

docker/init.sh

Fix haproxy init, eve-whmapper network shall be requested. Eve-whmapper container shall be init before haproxy container

Update docker init.sh

---

src/WHMapper.Tests/Services/Db/DbIntegrationTest.cs
src/WHMapper/Migrations/20240507153308_Update_Jump_Log_Properties_To_Nullable.Designer.cs
src/WHMapper/Migrations/20240507153308_Update_Jump_Log_Properties_To_Nullable.cs
src/WHMapper/Models/Db/WHJumpLog.cs
src/WHMapper/Pages/Mapper/CustomNode/EveSystemLink.cs
src/WHMapper/Pages/Mapper/LinkInfos/Overview.cs
src/WHMapper/Pages/Mapper/LinkInfos/Overview.razor
src/WHMapper/Pages/Mapper/Overview.cs

Manage link create manually (fix db with nullable value)

Show link status an d size on linkInfoOverview

---

src/WHMapper/Pages/Mapper/Overview.razor

It is now possible to hold the [Shift] key and then drag a selection box over multiple systems by holding the left mouse button.

Enable selection box for all maps

---

src/WHMapper/Pages/Mapper/SystemInfos/Overview.cs
src/WHMapper/Services/WHColor/WHColorHelper.cs

Floating point numbers should not be tested for equality csharpsquid:S1244

Do not check floating point equality with exact values, use a range instead.

---

src/WHMapper.Tests/AutoDomainDataAttribute.cs
src/WHMapper.Tests/AutoMoqDataAttribute.cs
src/WHMapper.Tests/DomainCustomization.cs
src/WHMapper.Tests/InlineAutoMoqDataAttribute.cs
src/WHMapper.Tests/Services/Anoik/AnoikServicesTests.cs
src/WHMapper.Tests/WHMapper.Tests.csproj
src/WHMapper/Services/Anoik/AnoikServices.cs
src/WHMapper/Services/Anoik/IAnoikServices.cs

Add test classes and add unit tests for AnoikServices

Add test classes and add unit tests for AnoikServices

---

src/WHMapper.Tests/Services/Anoik/AnoikDataSupplierTests.cs
src/WHMapper.Tests/Services/Anoik/AnoikFromJSONFileTest.cs
src/WHMapper.Tests/Services/Anoik/AnoikServiceTestConstants.cs
src/WHMapper.Tests/Services/Anoik/AnoikServicesTests.cs
src/WHMapper.Tests/WHHelper/EveWHMapperHelperTest.cs
src/WHMapper.Tests/appsettings.json
src/WHMapper/Program.cs
src/WHMapper/Services/Anoik/AnoikJsonDataSupplier.cs
src/WHMapper/Services/Anoik/AnoikServices.cs
src/WHMapper/Services/Anoik/IAnoikDataSupplier.cs
src/WHMapper/WHMapper.csproj
src/WHMapper/appsettings.json

I wanted to continue writing more unit tests. I've added a data supplier for AnoikServices so it's testable. I've add settings, fixed it in the DI container and added and mended tests.

AnoikService data supplier and unit tests

---

src/WHMapper/Pages/Mapper/Overview.cs
src/WHMapper/Repositories/WHMaps/WHMapRepository.cs
src/WHMapper/Repositories/WHRoutes/WHRouteRepository.cs
src/WHMapper/Repositories/WHSignatures/WHSignatureRepository.cs
src/WHMapper/Repositories/WHSystemLinks/WHSystemLinkRepository.cs
src/WHMapper/Repositories/WHSystems/WHSystemRepository.cs

Fix : Do not check floating point inequality with exact values, use a range instead.
Fix : Await ShowAsync instead.
Fix : Await CountAsync instead.
Fix : Await CreateDbContextAsync instead.

Optimization Reliability

---

src/WHMapper/Pages/Mapper/Overview.cs

fix : #282

---

src/WHMapper/Pages/Mapper/Signatures/Import.razor
src/WHMapper/Services/WHSignatures/WHSignatureHelper.cs

- fix signature update time and updater
- fix import sigs ui
- fix sigs import preview value

fix sigs scan import

---

deploy/docker/haproxy/conf/haproxy.cfg

Security check made by : https://securityheaders.com

improve HAPROXY security

---

src/WHMapper/Services/WHSignatures/IWHSignatureHelper.cs

Test made : 
EHR-038    Cosmic Signature    Wormhole        0,0%    4,79 AU
FSS-940    Cosmic Signature    Wormhole    Unstable Wormhole    100,0%    4'219'269 km
HKL-578    Cosmic Signature    Combat Site        0,0%    7,36 AU
MSQ-896    Cosmic Signature    Combat Site        0,0%    5,71 AU
ADK-818    Cosmic Signature    Data Site        0,0%    6,32 AU
AFM-958    Cosmic Signature    Data Site        0,0%    0,35 AU
BPI-985    Cosmic Signature    Gas Site    Minor Perimeter Reservoir    100,0%    9,96 AU
GUC-350    Cosmic Signature    Wormhole    Unstable Wormhole    100,0%    2 579 m
LOT-702    Cosmic Signature    Data Site        0,0%    12,65 AU
MOI-632    Cosmic Signature    Relic Site    Ruined Serpentis Monument Site    0,0%    5,68 AU
NTT-256    Cosmic Signature    Wormhole …

FIX import signature

---

.github/workflows/ci-cd.yaml
.github/workflows/publish-release.yml

Reverts pfh59/eve-whmapper#308

Revert "Update CI/CD workflows to include Open Containers image labels"

---

.github/workflows/ci-cd.yaml
src/WHMapper/Pages/Mapper/Map/Overview.cs

Refactor map loading logic to improve asynchronous processing and error handling

fix : slow loading

---

src/WHMapper/Services/EveMapper/EveMapperSearch.cs
src/WHMapper/Services/EveMapper/IEveMapperSearch.cs

- Enhance search functionality by adding strict mode parameter to search methods

- Fix : #325

---

src/WHMapper/Pages/Mapper/LinkInfos/Overview.cs
src/WHMapper/Pages/Mapper/LinkInfos/Overview.razor

Fix  jump history
